#!/bin/bash -e
# by komar@evologics.de

VER=0.12
PKG_DIR=src

DO_CLEAN=true
DO_DEV_SHELL=false

PROG=$(basename $0)

while getopts "ns" OPT; do
    case $OPT in
        n) DO_CLEAN=false            ;;
        s) DO_DEV_SHELL=true         ;;
        *) echo "Invalid option" >&2 ;;
    esac
done

shift $((OPTIND - 1))

if [ -z "$1" -o ! -d "$1" -o ! -e "$1/get" ]; then
    cat <<- END 1>&2
        Usage: $PROG plugin-dir 
        Make debian package for Trac Plugin

        -n  - do not remove sources after deb build
        -s  - run shell in prepared package directory before building
END
    exit 1
fi


cd $1
. ./get

set -x

DIRS=$(find $PKG_DIR -name setup.py)
for F in $DIRS; do
    PKG_DIR_CURR=$(dirname $F)
    cd $PKG_DIR_CURR
    python setup.py sdist
    cd -

    py2dsc $PKG_DIR_CURR/dist/*tar.gz

    pushd $(find deb_dist/* -maxdepth 0 -type d | grep -v orig)
    sed -i -e 's/\(Package: \)\(python-\(trac\)\?\)\?/\1trac-/' debian/control

    if $DO_DEV_SHELL; then
        if ! bash -i; then
            exit $?
        fi
    fi

    dpkg-buildpackage -b -d -us -uc
    popd

    pwd
    mv deb_dist/*deb .
    $DO_CLEAN && rm -r $PKG_DIR_CURR deb_dist

    cd ..
    PKG="$PKG $(ls -t $1/*deb | head -n 1)"
    cd - > /dev/null
    pwd
done
$DO_CLEAN && [ -d $PKG_DIR ] && rm -rf $PKG_DIR

set +x
echo ===================
echo sudo dpkg -i $PKG
